spring.application.name=Literalura
# Configuracion de la conexion a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME2}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de HIBERNATE (JPA)
# Controla como Hibernate gestiona el esquema de la base de datos
# UPDATE: Intenta actualizar el esquam existente para que coincida con las entidades JPA
spring.jpa.hibernate.dll-auto=update 
# Le indica a Hibernate qué dialecto SQL debe usar
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Imprime en la consola las consultas SQL que está ejecutando
spring.jpa.show-sql=true
# Formatea las consultas SQL que Hibernate imprime en la consola
spring.jpa.properties.hibernate.format_sql=true